### PR TITLE
Adding __hash__ method in Section class to allow for Section objects …

### PR DESCRIPTION
**Pull request by amhokies**
…to be used in sets

### CODE REVIEW

**Comment by kevincianfarini** [comment]
I like the idea of having a __hash__ function implemented but the way it's currently being done isn't as clean as it could possibly be. 

Because the __str__ function doesn't take into account some of the attributes of the Section class, although unlikely, it could allow for multiple sections that are unique to have the same hash value. I would suggest hashing on a tuple of the values that the section object holds.

Also, do you think you might be able to test this function a bit before another PR?

**Comment by amhokies** [comment]
Since the CRN is unique for each class, there shouldn't be different sections with the same hash value. Really, I could just hash the CRN instead of the entire string representation and it would be a similar outcome. I'll add tests for it sometime today.

**Comment by amhokies** [comment]
Or I could just make the CRN an integer and return that as a hash value. That would be more efficient and would ensure there are no collisions.

**Comment by kevincianfarini** [comment]
That would work

**Pull request merged**
